//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MF_Demand()
        {
            this.MF_DemandDate = new HashSet<MF_DemandDate>();
            this.MF_Project = new HashSet<MF_Project>();
        }
    
        public int Id_Demand { get; set; }
        public Nullable<int> Item { get; set; }
        public string Demand { get; set; }
        public int Id_Customer { get; set; }
        public Nullable<int> Id_Sector { get; set; }
    
        public virtual MF_Customer MF_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_DemandDate> MF_DemandDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Project> MF_Project { get; set; }
        public virtual MF_Sector MF_Sector { get; set; }
    }
}
