//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_DemandDate
    {
        public int Id_DemandDate { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> Id_Demand { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Id_WorkDate { get; set; }
    
        public virtual MF_Demand MF_Demand { get; set; }
        public virtual MF_WorkDate MF_WorkDate { get; set; }
    }
}
