//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_ExcelProceso
    {
        public int Id_ExcelProceso { get; set; }
        public int Id_Proceso { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
    
        public virtual MF_Proceso MF_Proceso { get; set; }
    }
}
