//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MF_Machine()
        {
            this.MF_OpMachine = new HashSet<MF_OpMachine>();
            this.MF_Part = new HashSet<MF_Part>();
        }
    
        public int Id_Machine { get; set; }
        public Nullable<int> Item { get; set; }
        public string Machine { get; set; }
        public Nullable<int> Id_Proceso { get; set; }
        public Nullable<int> Id_Sector { get; set; }
    
        public virtual MF_Sector MF_Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_OpMachine> MF_OpMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Part> MF_Part { get; set; }
        public virtual MF_Proceso MF_Proceso { get; set; }
    }
}
