//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_OpMachine
    {
        public int Id_OpMachine { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> Id_Part { get; set; }
        public Nullable<int> Id_Machine { get; set; }
        public Nullable<int> Id_Proceso { get; set; }
    
        public virtual MF_Machine MF_Machine { get; set; }
        public virtual MF_Part MF_Part { get; set; }
        public virtual MF_Proceso MF_Proceso { get; set; }
    }
}
