//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MF_Proceso()
        {
            this.MF_Machine = new HashSet<MF_Machine>();
            this.MF_OpMachine = new HashSet<MF_OpMachine>();
            this.MF_Part = new HashSet<MF_Part>();
            this.MF_Project = new HashSet<MF_Project>();
            this.MF_ExcelProceso = new HashSet<MF_ExcelProceso>();
        }
    
        public int Id_Proceso { get; set; }
        public string Proceso { get; set; }
        public Nullable<double> DiasIndustrial { get; set; }
        public Nullable<double> DiasMedical { get; set; }
        public Nullable<double> DiasProvee1 { get; set; }
        public Nullable<double> DiasProvee2 { get; set; }
        public Nullable<double> TurnoIndustrial { get; set; }
        public Nullable<double> TurnoMedical { get; set; }
        public Nullable<double> TurnoProvee1 { get; set; }
        public Nullable<double> TurnoProvee2 { get; set; }
        public Nullable<int> Id_DemandMonth { get; set; }
        public Nullable<int> Id_DemandYear { get; set; }
        public Nullable<bool> EnaIndu { get; set; }
        public Nullable<bool> EnaMed { get; set; }
        public Nullable<bool> EnaPro1 { get; set; }
        public Nullable<bool> EnaPro2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Machine> MF_Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_OpMachine> MF_OpMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Part> MF_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_Project> MF_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_ExcelProceso> MF_ExcelProceso { get; set; }
    }
}
