//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandMetalFab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_WorkDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MF_WorkDate()
        {
            this.MF_DemandDate = new HashSet<MF_DemandDate>();
        }
    
        public int Id_WorkDate { get; set; }
        public int Id_DemandMonth { get; set; }
        public int Id_DemandYear { get; set; }
        public int WorkWeeks { get; set; }
        public int WorkDays { get; set; }
    
        public virtual MF_DemandMonth MF_DemandMonth { get; set; }
        public virtual MF_DemandYear MF_DemandYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MF_DemandDate> MF_DemandDate { get; set; }
    }
}
